[Settings]
  ID = "f1ce39f5-19b3-4caa-a3c3-75e31ff368dd"

[build]
  publish = "public"
  command = "npm run test && gatsby build && bash <(curl -s https://codecov.io/bash)"
  Functions = ""
 
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
