[Settings]
  ID = "f1ce39f5-19b3-4caa-a3c3-75e31ff368dd"

[build]
  publish = "public"
  command = "gatsby build"
  Functions = ""
 
[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/contact-us-2/"
  to = "/park-info/"
  status = 301

[[redirects]]
  from = "/birthdays/"
  to = "/birthday-parties/"
  status = 301