[Settings]
  ID = "f1ce39f5-19b3-4caa-a3c3-75e31ff368dd"

[build]
  publish = "public"
  command = "npm run test && gatsby build && bash <(curl -s https://codecov.io/bash)"
  Functions = ""
 
[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
  # optional, defaults to scanning the current built version of the site
  # audit_url = 'https://charleston-fun-park.netlify.app'
  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.9