name: CI/CD

on:
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests and generate coverage report
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish preview to GitHub Pages
        uses: xmflsct/action-publish-gatsby-contentful@v1.1.0
        with:
          publishBranch: "prod" # Not required, default publishing branch is master
          token: ${{ secrets.GH_PAGES }} # Your personal access token of GitHub, read more below of how to obtain one and keep it safe
          name: "Kenny Elshoff" # Not required, default to action's maintainer
          email: "contact+cfp@kennyelshoff.com" # Not required, default to action's maintainer
          contentfulSpace: ${{ secrets.CONTENTFUL_SPACE_ID }} # Your Space ID in Contentful
          contentfulToken: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }} # Your access token of Contentful
